trigger:
  branches:
    include:
    - master
    - feature/*
  tags:
    include:
    - '*'

resources:
  repositories:
    - repository: recommended_practices
      type: github
      name: endjin/Endjin.RecommendedPractices.AzureDevopsPipelines.GitHub
      endpoint: vellum-dotnet-github
      ref: refs/heads/invokebuild-spike

jobs:
- template: templates/build.and.release.yml@recommended_practices
  parameters:
    vmImage: 'ubuntu-latest'
    service_connection_nuget_org: $(Endjin_Service_Connection_NuGet_Org)
    service_connection_github: $(Endjin_Service_Connection_GitHub)
    build_script: ./vellum-cli.build.ps1
    netSdkVersion: '3.x'
    prePublishReleaseArtifacts:
      - task: CopyFiles@2
        displayName: 'Copy .nuspec Generated NuGet Packages To Release Folder'
        inputs:
          SourceFolder: '$(Build.ArtifactStagingDirectory)'
          Contents: '*.nupkg'
          TargetFolder: '$(Build.ArtifactStagingDirectory)/Release/NuGet/Packages/$(Build.BuildID)'