// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace Vellum.Abstractions.Specs
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute()]
    public partial class ContentFragmentExtensibilityFeature
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private Microsoft.VisualStudio.TestTools.UnitTesting.TestContext _testContext;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "", "ContentFragmentExtensibility", null, global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
#line 1 "ContentFragmentExtensibility.feature"
#line hidden
        
        public virtual Microsoft.VisualStudio.TestTools.UnitTesting.TestContext TestContext
        {
            get
            {
                return this._testContext;
            }
            set
            {
                this._testContext = value;
            }
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.ClassInitializeAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync(Microsoft.VisualStudio.TestTools.UnitTesting.TestContext testContext)
        {
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupAttribute(Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupBehavior.EndOfClass)]
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestInitializeAttribute()]
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCleanupAttribute()]
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Microsoft.VisualStudio.TestTools.UnitTesting.TestContext>(_testContext);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        public virtual async global::System.Threading.Tasks.Task FeatureBackgroundAsync()
        {
#line 3
#line hidden
            global::Reqnroll.Table table1 = new global::Reqnroll.Table(new string[] {
                        "document",
                        "file"});
            table1.AddRow(new string[] {
                        "Blog with extensions",
                        "blog-with-extensions.md"});
#line 5
  await testRunner.GivenAsync("the following markdown files", ((string)(null)), table1, "Given ");
#line hidden
            global::Reqnroll.Table table2 = new global::Reqnroll.Table(new string[] {
                        "document",
                        "file"});
            table2.AddRow(new string[] {
                        "Blog with extensions",
                        "blog-with-extensions.html"});
#line 8
  await testRunner.GivenAsync("the following html files", ((string)(null)), table2, "Given ");
#line hidden
            global::Reqnroll.Table table3 = new global::Reqnroll.Table(new string[] {
                        "ContentType",
                        "Id",
                        "SpecPath"});
            table3.AddRow(new string[] {
                        "application/vnd.vellum.content.blogs+md",
                        "Blogs",
                        "../../blog-with-extensions.md"});
#line 11
  await testRunner.GivenAsync("the following content blocks", ((string)(null)), table3, "Given ");
#line hidden
#line 14
  await testRunner.GivenAsync("the \"Blogs\" ContentBlocks", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 15
  await testRunner.AndAsync("the \"Blog with extensions\" document", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 16
  await testRunner.AndAsync("we Create a Content Fragment", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
        }
        
        private static global::Io.Cucumber.Messages.Types.Source SourceFunc()
        {
            return new global::Io.Cucumber.Messages.Types.Source("ContentFragmentExtensibility.feature", "Feature: ContentFragmentExtensibility \r\n\r\nBackground:\r\n\r\n  Given the following ma" +
                    "rkdown files\r\n    | document             | file                    |\r\n    | Blog" +
                    " with extensions | blog-with-extensions.md |\r\n  Given the following html files\r\n" +
                    "    | document             | file                      |\r\n    | Blog with extens" +
                    "ions | blog-with-extensions.html |\r\n  Given the following content blocks\r\n    | " +
                    "ContentType                             | Id    | SpecPath                      " +
                    "|\r\n    | application/vnd.vellum.content.blogs+md | Blogs | ../../blog-with-exten" +
                    "sions.md |\r\n  Given the \"Blogs\" ContentBlocks\r\n  And the \"Blog with extensions\" " +
                    "document\r\n  And we Create a Content Fragment\r\n\r\nScenario: A markdown file with e" +
                    "xtensions gets converted into a Content Fragment with extensions\r\n  Then Content" +
                    " Fragment should contain\r\n    | ContentType                             | Date  " +
                    "           | Hash                                                             | " +
                    "Id    | Position | PublicationStatus | BodyHtmlDocumentName |\r\n    | application" +
                    "/vnd.vellum.content.blogs+md | 2022-11-05 06:30 | 58754666f4d7b6578f70dea23f2a24" +
                    "a3aa2d6771a91e8baed08874501557e9b2 | Blogs | 0        | Published         | Blog" +
                    " with extensions |\r\n  And the Content Fragment should contain the following Exte" +
                    "nsions:\r\n    | ContentType                                 |\r\n    | application/" +
                    "vnd.vellum.content.series+md    |\r\n    | application/vnd.vellum.content.promotio" +
                    "n+md |\r\n\r\nScenario: A Content Fragment with extensions generates a new dynamic e" +
                    "xtension type\r\n  When we do something", global::Io.Cucumber.Messages.Types.SourceMediaType.TEXT_X_CUCUMBER_GHERKIN_PLAIN);
        }
        
        private static global::Io.Cucumber.Messages.Types.GherkinDocument GherkinDocumentFunc()
        {
            return new global::Io.Cucumber.Messages.Types.GherkinDocument("ContentFragmentExtensibility.feature", new global::Io.Cucumber.Messages.Types.Feature(new global::Io.Cucumber.Messages.Types.Location(1, new System.Nullable<long>(1)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[0]), "en-US", "Feature", "ContentFragmentExtensibility", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.FeatureChild>(new global::Io.Cucumber.Messages.Types.FeatureChild[] {
                                new global::Io.Cucumber.Messages.Types.FeatureChild(null, new global::Io.Cucumber.Messages.Types.Background(new global::Io.Cucumber.Messages.Types.Location(3, new System.Nullable<long>(1)), "Background", "", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(5, new System.Nullable<long>(3)), "Given ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONTEXT, "the following markdown files", null, new global::Io.Cucumber.Messages.Types.DataTable(new global::Io.Cucumber.Messages.Types.Location(6, new System.Nullable<long>(5)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.TableRow>(new global::Io.Cucumber.Messages.Types.TableRow[] {
                                                                        new global::Io.Cucumber.Messages.Types.TableRow(new global::Io.Cucumber.Messages.Types.Location(6, new System.Nullable<long>(5)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.TableCell>(new global::Io.Cucumber.Messages.Types.TableCell[] {
                                                                                        new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(6, new System.Nullable<long>(7)), "document"),
                                                                                        new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(6, new System.Nullable<long>(30)), "file")}), "4302c4f37a9e54578293d83b6230aa88"),
                                                                        new global::Io.Cucumber.Messages.Types.TableRow(new global::Io.Cucumber.Messages.Types.Location(7, new System.Nullable<long>(5)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.TableCell>(new global::Io.Cucumber.Messages.Types.TableCell[] {
                                                                                        new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(7, new System.Nullable<long>(7)), "Blog with extensions"),
                                                                                        new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(7, new System.Nullable<long>(30)), "blog-with-extensions.md")}), "4303799f67f7e650867f7673e29bf9d8")})), "22a52cd063ec625592f4d3adc70fd623"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(8, new System.Nullable<long>(3)), "Given ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONTEXT, "the following html files", null, new global::Io.Cucumber.Messages.Types.DataTable(new global::Io.Cucumber.Messages.Types.Location(9, new System.Nullable<long>(5)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.TableRow>(new global::Io.Cucumber.Messages.Types.TableRow[] {
                                                                        new global::Io.Cucumber.Messages.Types.TableRow(new global::Io.Cucumber.Messages.Types.Location(9, new System.Nullable<long>(5)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.TableCell>(new global::Io.Cucumber.Messages.Types.TableCell[] {
                                                                                        new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(9, new System.Nullable<long>(7)), "document"),
                                                                                        new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(9, new System.Nullable<long>(30)), "file")}), "79b8d345b4db7c5a88d1a6af2f8fb431"),
                                                                        new global::Io.Cucumber.Messages.Types.TableRow(new global::Io.Cucumber.Messages.Types.Location(10, new System.Nullable<long>(5)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.TableCell>(new global::Io.Cucumber.Messages.Types.TableCell[] {
                                                                                        new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(10, new System.Nullable<long>(7)), "Blog with extensions"),
                                                                                        new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(10, new System.Nullable<long>(30)), "blog-with-extensions.html")}), "46cdf91548a1b55d90915e03375bb6f6")})), "97b57f39edadba5eba895c28e2e2f0ec"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(11, new System.Nullable<long>(3)), "Given ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONTEXT, "the following content blocks", null, new global::Io.Cucumber.Messages.Types.DataTable(new global::Io.Cucumber.Messages.Types.Location(12, new System.Nullable<long>(5)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.TableRow>(new global::Io.Cucumber.Messages.Types.TableRow[] {
                                                                        new global::Io.Cucumber.Messages.Types.TableRow(new global::Io.Cucumber.Messages.Types.Location(12, new System.Nullable<long>(5)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.TableCell>(new global::Io.Cucumber.Messages.Types.TableCell[] {
                                                                                        new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(12, new System.Nullable<long>(7)), "ContentType"),
                                                                                        new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(12, new System.Nullable<long>(49)), "Id"),
                                                                                        new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(12, new System.Nullable<long>(57)), "SpecPath")}), "e5ff8d41f056695e88a01965d9639b2c"),
                                                                        new global::Io.Cucumber.Messages.Types.TableRow(new global::Io.Cucumber.Messages.Types.Location(13, new System.Nullable<long>(5)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.TableCell>(new global::Io.Cucumber.Messages.Types.TableCell[] {
                                                                                        new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(13, new System.Nullable<long>(7)), "application/vnd.vellum.content.blogs+md"),
                                                                                        new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(13, new System.Nullable<long>(49)), "Blogs"),
                                                                                        new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(13, new System.Nullable<long>(57)), "../../blog-with-extensions.md")}), "8d30c4ff097b5e56a008316eb503089a")})), "97ed5e72aa00e155a0507aad63789f54"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(14, new System.Nullable<long>(3)), "Given ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONTEXT, "the \"Blogs\" ContentBlocks", null, null, "02588573f138a45b9ddacf3a10177165"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(15, new System.Nullable<long>(3)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "the \"Blog with extensions\" document", null, null, "623efc4cd86f7a5081cb725e79ce45e1"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(16, new System.Nullable<long>(3)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "we Create a Content Fragment", null, null, "3ad7599dc5945f5caf5c068917bd26b3")}), "9898eca331337f5b88e4ab61d6271e17"), null),
                                new global::Io.Cucumber.Messages.Types.FeatureChild(null, null, new global::Io.Cucumber.Messages.Types.Scenario(new global::Io.Cucumber.Messages.Types.Location(18, new System.Nullable<long>(1)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[0]), "Scenario", "A markdown file with extensions gets converted into a Content Fragment with exten" +
                                            "sions", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(19, new System.Nullable<long>(3)), "Then ", global::Io.Cucumber.Messages.Types.StepKeywordType.OUTCOME, "Content Fragment should contain", null, new global::Io.Cucumber.Messages.Types.DataTable(new global::Io.Cucumber.Messages.Types.Location(20, new System.Nullable<long>(5)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.TableRow>(new global::Io.Cucumber.Messages.Types.TableRow[] {
                                                                        new global::Io.Cucumber.Messages.Types.TableRow(new global::Io.Cucumber.Messages.Types.Location(20, new System.Nullable<long>(5)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.TableCell>(new global::Io.Cucumber.Messages.Types.TableCell[] {
                                                                                        new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(20, new System.Nullable<long>(7)), "ContentType"),
                                                                                        new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(20, new System.Nullable<long>(49)), "Date"),
                                                                                        new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(20, new System.Nullable<long>(68)), "Hash"),
                                                                                        new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(20, new System.Nullable<long>(135)), "Id"),
                                                                                        new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(20, new System.Nullable<long>(143)), "Position"),
                                                                                        new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(20, new System.Nullable<long>(154)), "PublicationStatus"),
                                                                                        new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(20, new System.Nullable<long>(174)), "BodyHtmlDocumentName")}), "4b45385986b41f5d8459050830e3495e"),
                                                                        new global::Io.Cucumber.Messages.Types.TableRow(new global::Io.Cucumber.Messages.Types.Location(21, new System.Nullable<long>(5)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.TableCell>(new global::Io.Cucumber.Messages.Types.TableCell[] {
                                                                                        new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(21, new System.Nullable<long>(7)), "application/vnd.vellum.content.blogs+md"),
                                                                                        new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(21, new System.Nullable<long>(49)), "2022-11-05 06:30"),
                                                                                        new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(21, new System.Nullable<long>(68)), "58754666f4d7b6578f70dea23f2a24a3aa2d6771a91e8baed08874501557e9b2"),
                                                                                        new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(21, new System.Nullable<long>(135)), "Blogs"),
                                                                                        new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(21, new System.Nullable<long>(143)), "0"),
                                                                                        new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(21, new System.Nullable<long>(154)), "Published"),
                                                                                        new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(21, new System.Nullable<long>(174)), "Blog with extensions")}), "cd170f89b178565a9ec9ad44abf69018")})), "b187e18571a0cc5fbf8203f155a4d0e1"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(22, new System.Nullable<long>(3)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "the Content Fragment should contain the following Extensions:", null, new global::Io.Cucumber.Messages.Types.DataTable(new global::Io.Cucumber.Messages.Types.Location(23, new System.Nullable<long>(5)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.TableRow>(new global::Io.Cucumber.Messages.Types.TableRow[] {
                                                                        new global::Io.Cucumber.Messages.Types.TableRow(new global::Io.Cucumber.Messages.Types.Location(23, new System.Nullable<long>(5)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.TableCell>(new global::Io.Cucumber.Messages.Types.TableCell[] {
                                                                                        new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(23, new System.Nullable<long>(7)), "ContentType")}), "77a8c8ebf483ec5fad8880a15c58e27e"),
                                                                        new global::Io.Cucumber.Messages.Types.TableRow(new global::Io.Cucumber.Messages.Types.Location(24, new System.Nullable<long>(5)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.TableCell>(new global::Io.Cucumber.Messages.Types.TableCell[] {
                                                                                        new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(24, new System.Nullable<long>(7)), "application/vnd.vellum.content.series+md")}), "a039cd4709755556bb8f7d836158559c"),
                                                                        new global::Io.Cucumber.Messages.Types.TableRow(new global::Io.Cucumber.Messages.Types.Location(25, new System.Nullable<long>(5)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.TableCell>(new global::Io.Cucumber.Messages.Types.TableCell[] {
                                                                                        new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(25, new System.Nullable<long>(7)), "application/vnd.vellum.content.promotion+md")}), "fbee68e6e0b4375c96f620c8a5134dee")})), "b8bfc109b43b1c509f860ba8aba7753a")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Examples>(new global::Io.Cucumber.Messages.Types.Examples[0]), "4d574103fd9dae54b6df0eb2afad4d63")),
                                new global::Io.Cucumber.Messages.Types.FeatureChild(null, null, new global::Io.Cucumber.Messages.Types.Scenario(new global::Io.Cucumber.Messages.Types.Location(27, new System.Nullable<long>(1)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[0]), "Scenario", "A Content Fragment with extensions generates a new dynamic extension type", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(28, new System.Nullable<long>(3)), "When ", global::Io.Cucumber.Messages.Types.StepKeywordType.ACTION, "we do something", null, null, "e76ce247cdde6c5e80df02ea0c84870e")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Examples>(new global::Io.Cucumber.Messages.Types.Examples[0]), "1d23f3517d215a5cb65d2e20befbcc53"))})), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Comment>(new global::Io.Cucumber.Messages.Types.Comment[0]));
        }
        
        private static global::System.Collections.Generic.IEnumerable<Io.Cucumber.Messages.Types.Pickle> PicklesFunc()
        {
            return new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Pickle>(new global::Io.Cucumber.Messages.Types.Pickle[] {
                        new global::Io.Cucumber.Messages.Types.Pickle("f716227be0860f5a92d07c089ae85fdf", "ContentFragmentExtensibility.feature", "A markdown file with extensions gets converted into a Content Fragment with exten" +
                                "sions", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(new global::Io.Cucumber.Messages.Types.PickleStepArgument(null, new global::Io.Cucumber.Messages.Types.PickleTable(new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTableRow>(new global::Io.Cucumber.Messages.Types.PickleTableRow[] {
                                                                new global::Io.Cucumber.Messages.Types.PickleTableRow(new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTableCell>(new global::Io.Cucumber.Messages.Types.PickleTableCell[] {
                                                                                new global::Io.Cucumber.Messages.Types.PickleTableCell("document"),
                                                                                new global::Io.Cucumber.Messages.Types.PickleTableCell("file")})),
                                                                new global::Io.Cucumber.Messages.Types.PickleTableRow(new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTableCell>(new global::Io.Cucumber.Messages.Types.PickleTableCell[] {
                                                                                new global::Io.Cucumber.Messages.Types.PickleTableCell("Blog with extensions"),
                                                                                new global::Io.Cucumber.Messages.Types.PickleTableCell("blog-with-extensions.md")}))}))), new System.Collections.Generic.List<string>(new string[] {
                                                        "22a52cd063ec625592f4d3adc70fd623"}), "84332596fafe6f56b8d49848f9803d98", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "the following markdown files"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(new global::Io.Cucumber.Messages.Types.PickleStepArgument(null, new global::Io.Cucumber.Messages.Types.PickleTable(new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTableRow>(new global::Io.Cucumber.Messages.Types.PickleTableRow[] {
                                                                new global::Io.Cucumber.Messages.Types.PickleTableRow(new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTableCell>(new global::Io.Cucumber.Messages.Types.PickleTableCell[] {
                                                                                new global::Io.Cucumber.Messages.Types.PickleTableCell("document"),
                                                                                new global::Io.Cucumber.Messages.Types.PickleTableCell("file")})),
                                                                new global::Io.Cucumber.Messages.Types.PickleTableRow(new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTableCell>(new global::Io.Cucumber.Messages.Types.PickleTableCell[] {
                                                                                new global::Io.Cucumber.Messages.Types.PickleTableCell("Blog with extensions"),
                                                                                new global::Io.Cucumber.Messages.Types.PickleTableCell("blog-with-extensions.html")}))}))), new System.Collections.Generic.List<string>(new string[] {
                                                        "97b57f39edadba5eba895c28e2e2f0ec"}), "0f2699175932585bb6cb65b01b9338e7", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "the following html files"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(new global::Io.Cucumber.Messages.Types.PickleStepArgument(null, new global::Io.Cucumber.Messages.Types.PickleTable(new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTableRow>(new global::Io.Cucumber.Messages.Types.PickleTableRow[] {
                                                                new global::Io.Cucumber.Messages.Types.PickleTableRow(new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTableCell>(new global::Io.Cucumber.Messages.Types.PickleTableCell[] {
                                                                                new global::Io.Cucumber.Messages.Types.PickleTableCell("ContentType"),
                                                                                new global::Io.Cucumber.Messages.Types.PickleTableCell("Id"),
                                                                                new global::Io.Cucumber.Messages.Types.PickleTableCell("SpecPath")})),
                                                                new global::Io.Cucumber.Messages.Types.PickleTableRow(new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTableCell>(new global::Io.Cucumber.Messages.Types.PickleTableCell[] {
                                                                                new global::Io.Cucumber.Messages.Types.PickleTableCell("application/vnd.vellum.content.blogs+md"),
                                                                                new global::Io.Cucumber.Messages.Types.PickleTableCell("Blogs"),
                                                                                new global::Io.Cucumber.Messages.Types.PickleTableCell("../../blog-with-extensions.md")}))}))), new System.Collections.Generic.List<string>(new string[] {
                                                        "97ed5e72aa00e155a0507aad63789f54"}), "71d8e1f12bff505fbf3dd2b64c52f174", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "the following content blocks"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "02588573f138a45b9ddacf3a10177165"}), "66bfc5560a7bd15296ed016ae275094d", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "the \"Blogs\" ContentBlocks"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "623efc4cd86f7a5081cb725e79ce45e1"}), "fe5b19408df6905b90fd394b961ca959", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "the \"Blog with extensions\" document"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "3ad7599dc5945f5caf5c068917bd26b3"}), "28487a39666f955398b480ff262796d6", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "we Create a Content Fragment"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(new global::Io.Cucumber.Messages.Types.PickleStepArgument(null, new global::Io.Cucumber.Messages.Types.PickleTable(new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTableRow>(new global::Io.Cucumber.Messages.Types.PickleTableRow[] {
                                                                new global::Io.Cucumber.Messages.Types.PickleTableRow(new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTableCell>(new global::Io.Cucumber.Messages.Types.PickleTableCell[] {
                                                                                new global::Io.Cucumber.Messages.Types.PickleTableCell("ContentType"),
                                                                                new global::Io.Cucumber.Messages.Types.PickleTableCell("Date"),
                                                                                new global::Io.Cucumber.Messages.Types.PickleTableCell("Hash"),
                                                                                new global::Io.Cucumber.Messages.Types.PickleTableCell("Id"),
                                                                                new global::Io.Cucumber.Messages.Types.PickleTableCell("Position"),
                                                                                new global::Io.Cucumber.Messages.Types.PickleTableCell("PublicationStatus"),
                                                                                new global::Io.Cucumber.Messages.Types.PickleTableCell("BodyHtmlDocumentName")})),
                                                                new global::Io.Cucumber.Messages.Types.PickleTableRow(new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTableCell>(new global::Io.Cucumber.Messages.Types.PickleTableCell[] {
                                                                                new global::Io.Cucumber.Messages.Types.PickleTableCell("application/vnd.vellum.content.blogs+md"),
                                                                                new global::Io.Cucumber.Messages.Types.PickleTableCell("2022-11-05 06:30"),
                                                                                new global::Io.Cucumber.Messages.Types.PickleTableCell("58754666f4d7b6578f70dea23f2a24a3aa2d6771a91e8baed08874501557e9b2"),
                                                                                new global::Io.Cucumber.Messages.Types.PickleTableCell("Blogs"),
                                                                                new global::Io.Cucumber.Messages.Types.PickleTableCell("0"),
                                                                                new global::Io.Cucumber.Messages.Types.PickleTableCell("Published"),
                                                                                new global::Io.Cucumber.Messages.Types.PickleTableCell("Blog with extensions")}))}))), new System.Collections.Generic.List<string>(new string[] {
                                                        "b187e18571a0cc5fbf8203f155a4d0e1"}), "35d7350cdbd9875c93144c1ace75b23b", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "Content Fragment should contain"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(new global::Io.Cucumber.Messages.Types.PickleStepArgument(null, new global::Io.Cucumber.Messages.Types.PickleTable(new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTableRow>(new global::Io.Cucumber.Messages.Types.PickleTableRow[] {
                                                                new global::Io.Cucumber.Messages.Types.PickleTableRow(new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTableCell>(new global::Io.Cucumber.Messages.Types.PickleTableCell[] {
                                                                                new global::Io.Cucumber.Messages.Types.PickleTableCell("ContentType")})),
                                                                new global::Io.Cucumber.Messages.Types.PickleTableRow(new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTableCell>(new global::Io.Cucumber.Messages.Types.PickleTableCell[] {
                                                                                new global::Io.Cucumber.Messages.Types.PickleTableCell("application/vnd.vellum.content.series+md")})),
                                                                new global::Io.Cucumber.Messages.Types.PickleTableRow(new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTableCell>(new global::Io.Cucumber.Messages.Types.PickleTableCell[] {
                                                                                new global::Io.Cucumber.Messages.Types.PickleTableCell("application/vnd.vellum.content.promotion+md")}))}))), new System.Collections.Generic.List<string>(new string[] {
                                                        "b8bfc109b43b1c509f860ba8aba7753a"}), "9865486b34dea65fb44b4e09aa49cefa", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "the Content Fragment should contain the following Extensions:")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[0]), new System.Collections.Generic.List<string>(new string[] {
                                        "4d574103fd9dae54b6df0eb2afad4d63"})),
                        new global::Io.Cucumber.Messages.Types.Pickle("f8116e774499c25cb6cde49f2c227b98", "ContentFragmentExtensibility.feature", "A Content Fragment with extensions generates a new dynamic extension type", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(new global::Io.Cucumber.Messages.Types.PickleStepArgument(null, new global::Io.Cucumber.Messages.Types.PickleTable(new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTableRow>(new global::Io.Cucumber.Messages.Types.PickleTableRow[] {
                                                                new global::Io.Cucumber.Messages.Types.PickleTableRow(new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTableCell>(new global::Io.Cucumber.Messages.Types.PickleTableCell[] {
                                                                                new global::Io.Cucumber.Messages.Types.PickleTableCell("document"),
                                                                                new global::Io.Cucumber.Messages.Types.PickleTableCell("file")})),
                                                                new global::Io.Cucumber.Messages.Types.PickleTableRow(new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTableCell>(new global::Io.Cucumber.Messages.Types.PickleTableCell[] {
                                                                                new global::Io.Cucumber.Messages.Types.PickleTableCell("Blog with extensions"),
                                                                                new global::Io.Cucumber.Messages.Types.PickleTableCell("blog-with-extensions.md")}))}))), new System.Collections.Generic.List<string>(new string[] {
                                                        "22a52cd063ec625592f4d3adc70fd623"}), "9c2be6cff1b43c52805d7b0be25adf93", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "the following markdown files"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(new global::Io.Cucumber.Messages.Types.PickleStepArgument(null, new global::Io.Cucumber.Messages.Types.PickleTable(new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTableRow>(new global::Io.Cucumber.Messages.Types.PickleTableRow[] {
                                                                new global::Io.Cucumber.Messages.Types.PickleTableRow(new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTableCell>(new global::Io.Cucumber.Messages.Types.PickleTableCell[] {
                                                                                new global::Io.Cucumber.Messages.Types.PickleTableCell("document"),
                                                                                new global::Io.Cucumber.Messages.Types.PickleTableCell("file")})),
                                                                new global::Io.Cucumber.Messages.Types.PickleTableRow(new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTableCell>(new global::Io.Cucumber.Messages.Types.PickleTableCell[] {
                                                                                new global::Io.Cucumber.Messages.Types.PickleTableCell("Blog with extensions"),
                                                                                new global::Io.Cucumber.Messages.Types.PickleTableCell("blog-with-extensions.html")}))}))), new System.Collections.Generic.List<string>(new string[] {
                                                        "97b57f39edadba5eba895c28e2e2f0ec"}), "e37407f4b50adf5e8f655b6f0225ce68", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "the following html files"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(new global::Io.Cucumber.Messages.Types.PickleStepArgument(null, new global::Io.Cucumber.Messages.Types.PickleTable(new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTableRow>(new global::Io.Cucumber.Messages.Types.PickleTableRow[] {
                                                                new global::Io.Cucumber.Messages.Types.PickleTableRow(new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTableCell>(new global::Io.Cucumber.Messages.Types.PickleTableCell[] {
                                                                                new global::Io.Cucumber.Messages.Types.PickleTableCell("ContentType"),
                                                                                new global::Io.Cucumber.Messages.Types.PickleTableCell("Id"),
                                                                                new global::Io.Cucumber.Messages.Types.PickleTableCell("SpecPath")})),
                                                                new global::Io.Cucumber.Messages.Types.PickleTableRow(new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTableCell>(new global::Io.Cucumber.Messages.Types.PickleTableCell[] {
                                                                                new global::Io.Cucumber.Messages.Types.PickleTableCell("application/vnd.vellum.content.blogs+md"),
                                                                                new global::Io.Cucumber.Messages.Types.PickleTableCell("Blogs"),
                                                                                new global::Io.Cucumber.Messages.Types.PickleTableCell("../../blog-with-extensions.md")}))}))), new System.Collections.Generic.List<string>(new string[] {
                                                        "97ed5e72aa00e155a0507aad63789f54"}), "0b4652793cd1255cbc0ef3e5552c5a74", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "the following content blocks"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "02588573f138a45b9ddacf3a10177165"}), "befb0d32219ebf5f8639821342f141f5", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "the \"Blogs\" ContentBlocks"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "623efc4cd86f7a5081cb725e79ce45e1"}), "2b39aaa0518f3f5593d7bba4dab0b84b", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "the \"Blog with extensions\" document"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "3ad7599dc5945f5caf5c068917bd26b3"}), "7d2ee2a220e10758b9625ddceba97908", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "we Create a Content Fragment"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "e76ce247cdde6c5e80df02ea0c84870e"}), "9de58149acabbe53a290ec4415ac293d", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "we do something")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[0]), new System.Collections.Generic.List<string>(new string[] {
                                        "1d23f3517d215a5cb65d2e20befbcc53"}))});
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages(new global::System.Func<Io.Cucumber.Messages.Types.Source>(ContentFragmentExtensibilityFeature.SourceFunc), new global::System.Func<Io.Cucumber.Messages.Types.GherkinDocument>(ContentFragmentExtensibilityFeature.GherkinDocumentFunc), new global::System.Func<System.Collections.Generic.IEnumerable<Io.Cucumber.Messages.Types.Pickle>>(ContentFragmentExtensibilityFeature.PicklesFunc));
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("A markdown file with extensions gets converted into a Content Fragment with exten" +
            "sions")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("A markdown file with extensions gets converted into a Content Fragment with exten" +
            "sions")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "ContentFragmentExtensibility")]
        public async global::System.Threading.Tasks.Task AMarkdownFileWithExtensionsGetsConvertedIntoAContentFragmentWithExtensions()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("A markdown file with extensions gets converted into a Content Fragment with exten" +
                    "sions", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 18
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 3
await this.FeatureBackgroundAsync();
#line hidden
                global::Reqnroll.Table table4 = new global::Reqnroll.Table(new string[] {
                            "ContentType",
                            "Date",
                            "Hash",
                            "Id",
                            "Position",
                            "PublicationStatus",
                            "BodyHtmlDocumentName"});
                table4.AddRow(new string[] {
                            "application/vnd.vellum.content.blogs+md",
                            "2022-11-05 06:30",
                            "58754666f4d7b6578f70dea23f2a24a3aa2d6771a91e8baed08874501557e9b2",
                            "Blogs",
                            "0",
                            "Published",
                            "Blog with extensions"});
#line 19
  await testRunner.ThenAsync("Content Fragment should contain", ((string)(null)), table4, "Then ");
#line hidden
                global::Reqnroll.Table table5 = new global::Reqnroll.Table(new string[] {
                            "ContentType"});
                table5.AddRow(new string[] {
                            "application/vnd.vellum.content.series+md"});
                table5.AddRow(new string[] {
                            "application/vnd.vellum.content.promotion+md"});
#line 22
  await testRunner.AndAsync("the Content Fragment should contain the following Extensions:", ((string)(null)), table5, "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("A Content Fragment with extensions generates a new dynamic extension type")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("A Content Fragment with extensions generates a new dynamic extension type")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "ContentFragmentExtensibility")]
        public async global::System.Threading.Tasks.Task AContentFragmentWithExtensionsGeneratesANewDynamicExtensionType()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "1";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("A Content Fragment with extensions generates a new dynamic extension type", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 27
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 3
await this.FeatureBackgroundAsync();
#line hidden
#line 28
  await testRunner.WhenAsync("we do something", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
