<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace />
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Vellum.Abstractions\Vellum.Abstractions.csproj" />
    <ProjectReference Include="..\Vellum.Middleware.Abstractions\Vellum.Middleware.Abstractions.csproj" />
  </ItemGroup>

</Project>